return {
    [1] = {
        MaxItemSpawn = 100,
        SpawnInterval = .75,
        CoinReward = 50,
        BarrierFolder = workspace.Map.Barriers.Round1
    },
    [2] = {
        MaxItemSpawn = 130,
        SpawnInterval = .6,
        CoinReward = 75,
        BarrierFolder = workspace.Map.Barriers.Round2
    },
    [3] = {
        MaxItemSpawn = 130,
        SpawnInterval = .45,
        CoinReward = 125,
        BarrierFolder = workspace.Map.Barriers.Round3
    },
    [4] = {
        MaxItemSpawn = 120,
        SpawnInterval = .3,
        CoinReward = 200,
        BarrierFolder = workspace.Map.Barriers.Round4
    },
}