return {
	[1] = {
		MaxItemSpawn = 100,
		SpawnInterval = 0.6,
		CoinReward = 50,
		BarrierFolder = workspace.Map.Barriers.Round1,
	},
	[2] = {
		MaxItemSpawn = 130,
		SpawnInterval = 0.525,
		CoinReward = 75,
		BarrierFolder = workspace.Map.Barriers.Round2,
	},
	[3] = {
		MaxItemSpawn = 130,
		SpawnInterval = 0.45,
		CoinReward = 125,
		BarrierFolder = workspace.Map.Barriers.Round3,
	},
	[4] = {
		MaxItemSpawn = 120,
		SpawnInterval = 0.3,
		CoinReward = 200,
		BarrierFolder = workspace.Map.Barriers.Round4,
	},
}
