return {
    [1] = {
        MaxItemSpawn = 50,
        SpawnInterval = .75,
        BarrierFolder = workspace.Map.Barriers.Round1
    },
    [2] = {
        MaxItemSpawn = 50,
        SpawnInterval = .6,
        BarrierFolder = workspace.Map.Barriers.Round2
    },
    [3] = {
        MaxItemSpawn = 50,
        SpawnInterval = .45,
        BarrierFolder = workspace.Map.Barriers.Round3
    },
    [4] = {
        MaxItemSpawn = 50,
        SpawnInterval = .3,
        BarrierFolder = workspace.Map.Barriers.Round4
    },
}